### PR TITLE
Handle focusing-outlet on last route node template

### LINKED ISSUE #15: Support focusing outlet on the end of the route tree
If there's a `{{focusing-outlet}}` at the end of a route tree, it will fail to render anything and throw an error. The default ember `{{outlet}}` gracefully works in this case, so should focusing-outlet.

### Reproduction
1. Clone https://github.com/sivakumar-kailasam/a
2. Run `ember server`

### Actual
screen shot 2016-04-16 at 11 53 30 pm
### Expected
Shouldn't throw an error even if there's no sub-routes to render inside it.

### PR DESCRIPTION
**Pull request by sivakumar-kailasam**
Fixes #15

### CODE REVIEW

File: app/components/focusing-outlet.js [hunk 1]
```diff
@@ -57,7 +57,13 @@ let FocusingOutlet = Ember.Component.extend({
       let pivotHandler = owner.get('_stashedHandlerInfos.pivotHandler.handler.routeName');
 
       let outletName = this.get('outletName');
-      let currentRoute = outletState[outletName].render.name;
+      let outletObj = outletState[outletName];
```
Comment (nathanhammond) [inline app/components/focusing-outlet.js]: How about:
```javascript
let currentRoute = Ember.get(outletState, outletName+'.render.name')
if (currentRoute === undefined) { return; }
```

File: tests/dummy/app/templates/application.hbs [hunk 2]
```diff
@@ -7,6 +7,7 @@
         <li>{{#link-to 'messages'}}Messages{{/link-to}}</li>
         <li>{{#link-to 'feed'}}Feed{{/link-to}}</li>
         <li>{{#link-to 'profile'}}Profile{{/link-to}}</li>
+        <li>{{#link-to 'about.us'}}About us{{/link-to}}</li>
```
Comment (nathanhammond) [inline tests/dummy/app/templates/application.hbs]: Since we only use these routes for automated testing let's omit the link here.

File: tests/dummy/app/templates/about.hbs [hunk 3]
```diff
@@ -0,0 +1,4 @@
+<h2>About Us</h2>
+<div>
```
Comment (nathanhammond) [inline tests/dummy/app/templates/about.hbs]: Drop `<div>`... it's wrapped by default.

File: tests/dummy/app/router.js [hunk 4]
```diff
@@ -16,6 +16,11 @@ Router.map(function() {
     this.route('message', {path: "/:id"});
   });
 
+  // Routes to test focusing outlet on last route in a route path
+  this.route('about', function() {
+    this.route('us');
```
Comment (nathanhammond) [inline tests/dummy/app/router.js]: We can probably test this at just the `about` level, no need for the `us` route? If it doesn't fail with just `about` I'd like to add test cases for both. :smile:

File: tests/acceptance/focus-test.js [hunk 5]
```diff
@@ -97,3 +97,10 @@ test('Linking to descendant routes with local error states.', function(assert) {
   visit('/iso-parent/boom');
   andThen(() => { assert.equal(checkFocus(), 'Global Error'); });
 });
+
+test('Should load an end route with a focusing outlet without any errors', function(assert) {
```
Comment (nathanhammond) [inline tests/acceptance/focus-test.js]: `Should load leaf routes with a spurious focusing outlet without any errors.`

File: app/components/focusing-outlet.js (hunk 1 above)
Comment (Robdel12) [inline app/components/focusing-outlet.js]: Let's go futher :P
```javascript
let currentRoute = Ember.get(outletState, `${outletName}.render.name`)
if (currentRoute === undefined) { return; }
```

Comment (sivakumar-kailasam) [inline app/components/focusing-outlet.js]: Much cleaner 👍

File: app/components/focusing-outlet.js [hunk 6]
```diff
@@ -57,7 +59,11 @@ let FocusingOutlet = Ember.Component.extend({
       let pivotHandler = owner.get('_stashedHandlerInfos.pivotHandler.handler.routeName');
 
       let outletName = this.get('outletName');
-      let currentRoute = outletState[outletName].render.name;
+
+      let currentRoute = get(outletState, `${outletName}.render.name`);
+      if (isEmpty(currentRoute)) {
```
Comment (nathanhammond) [inline app/components/focusing-outlet.js]: Since we know that it will either be a string or `undefined` [`isEmpty`](https://github.com/emberjs/ember.js/blob/v2.5.0/packages/ember-metal/lib/is_empty.js) is overkill.

File: app/components/focusing-outlet.js [hunk 7]
```diff
@@ -1,5 +1,7 @@
 import Ember from "ember";
 
+const { isEmpty, get } = Ember;
```
Comment (nathanhammond) [inline app/components/focusing-outlet.js]: Good call on destructuring.

**Comment by sivakumar-kailasam** [comment]
@nathanhammond everything's been taken care of :smile:

**Comment by nathanhammond** [comment]
Looks perfect! Thanks for the work @sivakumar-kailasam!
